# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pagination.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.searchBtn.setGeometry(QtCore.QRect(20, 20, 120, 50))
        self.searchBtn.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.searchBtn.setFont(font)
        self.searchBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchBtn.setMouseTracking(True)
        self.searchBtn.setStyleSheet("")
        self.searchBtn.setObjectName("searchBtn")
        self.searchTxt = QtWidgets.QLineEdit(self.centralwidget)
        self.searchTxt.setGeometry(QtCore.QRect(160, 20, 600, 50))
        self.searchTxt.setMinimumSize(QtCore.QSize(600, 50))
        self.searchTxt.setObjectName("searchTxt")
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setGeometry(QtCore.QRect(10, 90, 780, 400))
        self.tableView.setObjectName("tableView")
        self.itemBtn = QtWidgets.QPushButton(self.centralwidget)
        self.itemBtn.setGeometry(QtCore.QRect(20, 510, 120, 50))
        self.itemBtn.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.itemBtn.setFont(font)
        self.itemBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.itemBtn.setMouseTracking(True)
        self.itemBtn.setObjectName("itemBtn")
        self.brandBtn = QtWidgets.QPushButton(self.centralwidget)
        self.brandBtn.setGeometry(QtCore.QRect(150, 510, 120, 50))
        self.brandBtn.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.brandBtn.setFont(font)
        self.brandBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.brandBtn.setMouseTracking(True)
        self.brandBtn.setObjectName("brandBtn")
        self.closeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.closeBtn.setGeometry(QtCore.QRect(660, 510, 120, 50))
        self.closeBtn.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.closeBtn.setFont(font)
        self.closeBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeBtn.setMouseTracking(True)
        self.closeBtn.setObjectName("closeBtn")
        self.enterBtn = QtWidgets.QPushButton(self.centralwidget)
        self.enterBtn.setGeometry(QtCore.QRect(530, 510, 120, 50))
        self.enterBtn.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.enterBtn.setFont(font)
        self.enterBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.enterBtn.setMouseTracking(True)
        self.enterBtn.setObjectName("enterBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchBtn.setText(_translate("MainWindow", "SEARCH"))
        self.itemBtn.setText(_translate("MainWindow", "ITEM"))
        self.brandBtn.setText(_translate("MainWindow", "BRAND"))
        self.closeBtn.setText(_translate("MainWindow", "CLOSE"))
        self.enterBtn.setText(_translate("MainWindow", "ENTER"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
